package by.doitnow.ownexception;

public class NegativeRomeResult extends Exception{
}
